Relax install constraints on dev bootstrap
This is because:

```
root@tba-py3-docker:/tba# pip install blinker==1.5
Collecting blinker==1.5                                                                                                Using cached blinker-1.5-py2.py3-none-any.whl (12 kB)
Installing collected packages: blinker
  Attempting uninstall: blinker
    Found existing installation: blinker 1.4
ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

And this just seems to be dependend on by everything:

```
root@tba-py3-docker:/tba# dpkg -S /usr/lib/python3/dist-packages/blinker/__init__.py
python3-blinker: /usr/lib/python3/dist-packages/blinker/__init__.py
root@tba-py3-docker:/tba# apt-cache rdepends --installed python3-blinker
python3-blinker
Reverse Depends:
  python3-oauthlib
root@tba-py3-docker:/tba# apt-cache rdepends --installed python3-oauthlib
python3-oauthlib
Reverse Depends:
  python3-lazr.restfulclient
root@tba-py3-docker:/tba# apt-cache rdepends --installed python3-lazr-restfulcient
E: No packages found
root@tba-py3-docker:/tba# apt-cache rdepends --installed python3-lazr-restfulclient
E: No packages found
root@tba-py3-docker:/tba# apt-cache rdepends --installed python3-lazr.restfulclient
python3-lazr.restfulclient
Reverse Depends:
  python3-launchpadlib
root@tba-py3-docker:/tba# apt-cache rdepends --installed python3-launchpadlib
python3-launchpadlib
Reverse Depends:
  python3-software-properties
  python3-software-properties
```

So let's just make our bootstrap overwrite this, even if it has the
potential to get somewhat sketchy in the future